### PR TITLE
Imporve Fugitive commit message

### PR DESCRIPTION
**Pull request by albertorestifo**
I added a simple rule that improves the subject line when writing a commit message with Fugitive:

**Current:**

current

**After change:**

After

### CODE REVIEW

**Comment by atelierbram** [comment]
Thanks for this, it's appreciated. 

About the Airline-support: I will have to look into this plugin (which I have not used until now) to add a light-variation template. Note to self: Will have to put the commands for those Airline themes in a seperate `io-airline.sh` file, consider to _not_ generate them to keep the repo lean.

**Comment by albertorestifo** [comment]
Oh no, I did not realise my commits with the airline theme where being sent to the PR too!

I suggest you revert the change: it's not quite working properly yet, I was experimenting with it.

I planned to do a PR later on with everything properly set.

Sorry for that!

Edit:

I can create a new PR with just the original fix so you can simply revert this merge, if you like

**Comment by atelierbram** [comment]
Thanks, either way will work.

**Comment by albertorestifo** [comment]
Ok, revert this merge and when I have a minute I'll create a new PR.

Sorry for the mistake :bowtie:

**Comment by atelierbram** [comment]
Oh, now I just pulled it in, removed the Airline stuff, and pushed it back up, should be good now. Thanks again, I will look into Airline, and will think of how to best integrate this in here. Maybe it's an idea to just have the templates in here for Base16-Builder, and have the output for the themes in a dedicated repo, something like `Base2Tone-vim-airline`.

**Comment by atelierbram** [comment]
@albertorestifo Just wanted to notify you that I have been thinking on how to integrate Airline, and have decided it will be best to let that be it's own thing, so a dedicated Base2Tone-vim-airline repo. I will be experimenting with this as well, and was thinking of using the Zenburn-theme as a model, for the following reason:
The themes already look good with Zenburn, because Zenburn-airline picks up the colors from the main theme, which makes all the sense in the world to me for this Base2Tone/DuoTone concept with this UX-pattern. Please let me know if you have any thoughts on, or questions about this.

**Comment by albertorestifo** [comment]
@atelierbram You solved me a bit of a mistery there!

When I first started using Base2Tone I though Airline support was already there, now I know it's why I was previously using Zenburn. I agree their approach makes a ton of sense.

My advice is against keeping them in a separate repo: the most recentcly createm themes who support ailrine all seem to include the theme in the original repo.

It's not a big deal in either way anyway. Ping me if you need any help.

**Comment by atelierbram** [comment]
@albertorestifo Thanks for the feedback, is was in fact helpful breaking my indecision on the issue of repo-structure. 
So although I did start using Zenburn as a model, I _could not_ make the `_modified`-styles work with this (a crucial feature IMO), which is too bad. I'm just not a programmer, so maybe this function tripped me up .... Anyway, life is too short, so I hacked away on the default dark-theme, which comes with some clear documentation in the comments and could make faster progress. 

There are still two issues with this:
1. no support for x-term 256 (with Vim in terminals without truecolor support)
2. the renaming of the files forced by the naming-convention for airline (in relation to Base16-Builder quirks)

On one: again, life is too short, on two, see the README, instead of  `Base2Tone-<scheme>-dark` it is now: `Base2Tone_<scheme>Dark  ` , _... sorry for the inconvenience_.

Thanks again, without your initial effort, there would not have been Airline support for these themes right now ;)

**Pull request merged**
